//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ReportsOcrAndSearch
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Report.
    /// </summary>
    // *** Start programmer edit section *** (Report CustomAttributes)

    // *** End programmer edit section *** (Report CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ReportE", new string[] {
            "reportFile as \'Report file\'"})]
    [View("ReportL", new string[] {
            "reportFile as \'Report file\'"})]
    public class Report : ICSSoft.STORMNET.DataObject
    {

        private ICSSoft.STORMNET.UserDataTypes.WebFile freportFile;

        // *** Start programmer edit section *** (Report CustomMembers)

        // *** End programmer edit section *** (Report CustomMembers)


        /// <summary>
        /// reportFile.
        /// </summary>
        // *** Start programmer edit section *** (Report.reportFile CustomAttributes)

        // *** End programmer edit section *** (Report.reportFile CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile reportFile
        {
            get
            {
                // *** Start programmer edit section *** (Report.reportFile Get start)

                // *** End programmer edit section *** (Report.reportFile Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.freportFile;
                // *** Start programmer edit section *** (Report.reportFile Get end)

                // *** End programmer edit section *** (Report.reportFile Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Report.reportFile Set start)

                // *** End programmer edit section *** (Report.reportFile Set start)
                this.freportFile = value;
                // *** Start programmer edit section *** (Report.reportFile Set end)

                // *** End programmer edit section *** (Report.reportFile Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ReportE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportE", typeof(IIS.ReportsOcrAndSearch.Report));
                }
            }

            /// <summary>
            /// "ReportL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportL", typeof(IIS.ReportsOcrAndSearch.Report));
                }
            }
        }
    }
}

