version: '3'

services:
  app:
    image: reportsocrandsearch/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - OCRFileStoragePath=/var/reportspdf
      - BackendRoot=http://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;
    volumes:
      - REPORTSPDF:/var/reportspdf

  app-postgres-db:
    image: reportsocrandsearch/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
      
  ocr-service:
    image: reportsocrandsearch/ocr-service-tesseract
    volumes:
      - REPORTSPDF:/var/reportspdf

volumes:
  DB:
  REPORTSPDF:
