version: '3'

services:
  app:
    image: reportsocrandsearch/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=/var/reportspdf
      - BackendRoot=http://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;
      - ElasticUrl=http://elasticsearch:9200
    volumes:
      - REPORTSPDF:/var/reportspdf

  app-postgres-db:
    image: reportsocrandsearch/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
      
  ocr-service:
    image: reportsocrandsearch/ocr-service-tesseract
    volumes:
      - REPORTSPDF:/var/reportspdf
    ports:
      - 6600:80
    environment:
      - ElasticUrl=http://elasticsearch:9200
      - ElasticDocumentsIndex=pdf-documents

  elasticsearch:
    image: reportsocrandsearch/elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
        - 'xpack.security.enabled=false'
        - 'discovery.type=single-node'
        - 'bootstrap.memory_lock=true'
        - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    cap_add:
        - IPC_LOCK

volumes:
  DB:
  REPORTSPDF:
